# Generated by Django 4.2.5 on 2023-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='uiSettings',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
