# Generated by Django 4.2.5 on 2023-09-25 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_task_uisettings_uisetting'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='card_color',
            field=models.CharField(choices=[('default', 'Default'), ('bg-primary', 'Primary'), ('bg-secondary', 'Secondary'), ('bg-success', 'Success'), ('bg-danger', 'Danger'), ('bg-warning', 'Warning'), ('bg-info', 'Info'), ('bg-light', 'Light'), ('bg-dark', 'Dark'), ('bg-white', 'White')], default='default', max_length=14),
        ),
        migrations.AddField(
            model_name='task',
            name='font_color',
            field=models.CharField(choices=[('default', 'Default'), ('text-primary', 'Primary'), ('text-secondary', 'Secondary'), ('text-success', 'Success'), ('text-danger', 'Danger'), ('text-warning', 'Warning'), ('text-info', 'Info'), ('text-light', 'Light'), ('text-dark', 'Dark'), ('text-white', 'White')], default='default', max_length=14),
        ),
        migrations.AddField(
            model_name='task',
            name='font_family',
            field=models.CharField(choices=[('default', 'Default'), ('Consolas', 'Consolas'), ('Segoe Print', 'Segoe Print'), ('Gabriola', 'Gabriola')], default='default', max_length=14),
        ),
        migrations.DeleteModel(
            name='UiSetting',
        ),
    ]
